### ISSUE TITLE
ventura 

### ISSUE THREAD

**Issue by arushsarna** [Andrej-Antipov/X99-K9-Machinist-Hackintosh#2]
for some reason i am not able to update to ventura , it keeps restarting in a boot loop , can you please check

**Comment by Andrej-Antipov** [comment]
You need to use EFI with an updated Ventura OpenCore, drivers and kexts. Since I installed Ventura on this computer, several more beta versions have been released. So you need to download EFI for Ventura and update EFI drivers and kexts in this. You can even use OpenCore 0.8.3 - replacing OpenCore 0.8.2 files boot.efi and OpenCore.efi, and in the Drivers and Kexts folders with newer beta versions. They can be taken ready here. [Dortania Builds](https://dortania.github.io/builds/)
I don't have access to this hardware now, I'll have it later, maybe only in the fall.
